[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c",  "tmux attach || tmux"]

[env]
term = "xterm-256color"

[scrolling]
history = 5000

[window]
decorations = "None"
opacity = 0.72
startup_mode = "Maximized"
blur = true
padding = {x=3, y=3}
dynamic_padding = true

[font]
normal = {family = "JetBrainsMono NerdFont", style="SemiBold"}
size = 10

[cursor]
style = {shape = "Block", blinking="On"}
blink_timeout = 0
unfocused_hollow = false

[terminal]
