--require("core.plugin_config.bufferline")
require("core.plugin_config.conform")
require("core.plugin_config.lsp_config")
require("core.plugin_config.netrw")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.nvim-lint")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.telescope")
